classes:
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
- system.salt.control.virt
- system.salt.control.cluster.openstack_benchmark_single
- cluster.vlab.infra.k8s-vms
- cluster.vlab.infra.ceph-vms
- cluster.vlab.infra.cmp-vms
- cluster.vlab.infra.gtw-vms
- cluster.vlab.infra
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    deploy_nic: ens3
    primary_first_nic: ens4
    primary_second_nic: eth2
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.benchmark:
          cpu: 2
          disk_profile: small
          net_profile: newdefault
          ram: 4096
        kubernetes.control:
          net_profile: private
        kubernetes.compute:
          net_profile: private
#      cluster:
#        internal:
#          node:
#            bmk01:
#              provider: ${_param:infra_kvm_node04_hostname}.${_param:cluster_domain}
  virt:
    nic:
      newdefault:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
      proxy:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
        - name: eth2
          bridge: br_proxy
          model: virtio
      private:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
        - name: eth2
          bridge: br_private
          model: virtio
      cephnet:
        - name: eth0
          bridge: br_mgm
          model: virtio
        - name: eth1
          bridge: br_ctl
          model: virtio
        - name: eth2
          bridge: br_proxy
          model: virtio


  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
        ens4:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:primary_first_nic}
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          use_interfaces:
          - ${_param:deploy_nic}
          name_servers:
          - ${_param:dns_server01}
          - ${_param:dns_server02}
        ens4.101:
          name: ${_param:primary_first_nic}.${_param:control_vlan}
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - ${_param:primary_first_nic}
        ens4.102:
          name: ${_param:primary_first_nic}.${_param:tenant_vlan}
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - ${_param:primary_first_nic}
        ens4.103:
          name: ${_param:primary_first_nic}.${_param:proxy_vlan}
          enabled: true
          proto: manual
          type: vlan
          use_interfaces:
          - ${_param:primary_first_nic}
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          use_interfaces:
          - ${_param:primary_first_nic}.${_param:control_vlan}
        br_proxy:
          enabled: true
          type: bridge
          proto: manual
          use_interfaces:
          - ${_param:primary_first_nic}.${_param:proxy_vlan}
        br_private:
          enabled: true
          type: bridge
          proto: manual
          use_interfaces:
          - ${_param:primary_first_nic}.${_param:tenant_vlan}
  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./
